name: Docker CI

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build -t docker.pkg.github.com/readyaicode-2020/spork/spork:version-$GITHUB_RUN_NUMBER .
    - name: Login to Github Registry
      run: echo ${{ secrets.GITHUB_TOKEN }} | docker login docker.pkg.github.com -u ReadyAiCode-2020 --password-stdin
    - name: Pushing the Docker image
      run: docker push docker.pkg.github.com/readyaicode-2020/spork/spork:version-$GITHUB_RUN_NUMBER
